package com.example.demo.url.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.http.HttpStatus;

import java.time.LocalDateTime;

/**
 * DTO for representing the response of URL-related operations.
 * Includes details such as the shortened URL, original URL, creation date, author, and status messages.
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@NoArgsConstructor
public class UrlResponse {

    /**
     * The shortened URL generated by the system.
     */
    private String shortUrl;

    /**
     * The original long URL provided by the user.
     */
    private String longUrl;

    /**
     * The date and time when the shortened URL was created.
     */
    private LocalDateTime createdAt;

    /**
     * The username of the person who created the shortened URL.
     */
    private String author;

    /**
     * A message indicating the success or failure of the operation.
     */
    private String message;

    /**
     * The HTTP status associated with the response.
     * This field is ignored in the serialized JSON output.
     */
    @JsonIgnore
    private HttpStatus status;

    /**
     * Constructs a successful URL response with the provided details.
     *
     * @param shortUrl  The shortened URL.
     * @param longUrl   The original URL.
     * @param createdAt The creation date and time of the URL.
     * @param author    The username of the creator.
     * @param status    The HTTP status of the operation.
     */
    public UrlResponse(String shortUrl,
                       String longUrl,
                       LocalDateTime createdAt,
                       String author,
                       String message,
                       HttpStatus status) {
        this.shortUrl = shortUrl;
        this.longUrl = longUrl;
        this.createdAt = createdAt;
        this.author = author;
        this.message = message;
        this.status = status;
    }

    /**
     * Constructs a failed URL response with the provided message and status.
     *
     * @param message The failure message.
     * @param status  The HTTP status of the operation.
     */
    public UrlResponse(String message, HttpStatus status) {
        this.message = message;
        this.status = status;
    }

    /**
     * Static factory method to create a successful URL response.
     *
     * @param shortUrl  The shortened URL.
     * @param longUrl   The original URL.
     * @param createdAt The creation date and time of the URL.
     * @param author    The username of the creator.
     * @param status    The HTTP status of the operation.
     * @return A new instance of {@link UrlResponse}.
     */
    public static UrlResponse success(String shortUrl,
                                      String longUrl,
                                      LocalDateTime createdAt,
                                      String author,
                                      String message,
                                      HttpStatus status) {
        return new UrlResponse(shortUrl, longUrl, createdAt, author, message, status);
    }

    /**
     * Static factory method to create a failed URL response.
     *
     * @param message The failure message.
     * @param status  The HTTP status of the operation.
     * @return A new instance of {@link UrlResponse}.
     */
    public static UrlResponse failed(String message, HttpStatus status) {
        return new UrlResponse(message, status);
    }
}
