package com.example.demo.url;

import com.example.demo.user.User;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a URL in the system.
 * This class is mapped to the "urls" table in the "url_shortener" schema.
 *
 * <p> The class is annotated with {@link jakarta.persistence.Entity},
 * {@link jakarta.persistence.Table}, {@link jakarta.persistence.Id},
 * {@link jakarta.persistence.GeneratedValue}, {@link jakarta.persistence.GenerationType},
 * and {@link lombok.Data}, {@link lombok.AllArgsConstructor}, {@link lombok.NoArgsConstructor},
 * {@link lombok.Builder} to define the entity and automatically generate common methods. </p>
 * <p> This class has a Many-to-One relationship with the {@link User} entity.
 * * The {@code user} field represents the user associated with this URL.
 * * This relationship is eagerly fetched, meaning that data is loaded immediately when accessing this field. </p>
 */
@Entity
@Table(schema = "url_shortener", name = "urls")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Url {

    /**
     * Unique identifier for the URL entity.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The original long URL.
     * This field stores the complete URL that needs to be shortened.
     */
    @Column(name = "long_url", length = 2000, nullable = false)
    private String longUrl;

    /**
     * The generated short URL.
     * This field contains the shortened version of the long URL, unique across the system.
     */
    @Column(name = "short_url", length = 10, nullable = false, unique = true)
    private String shortUrl;

    /**
     * The user associated with this URL.
     * This is a Many-to-One relationship, linking each URL to the corresponding User entity.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User user;
}
