package com.example.demo.user;

import com.example.demo.url.Url;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

/**
 * Entity class representing a User in the system.
 * This class is mapped to the "users" table in the "url_shortener" schema.
 *
 * <p> The class is annotated with {@link jakarta.persistence.Entity},
 * {@link jakarta.persistence.Table}, {@link jakarta.persistence.Id},
 * {@link jakarta.persistence.GeneratedValue}, {@link jakarta.persistence.GenerationType},
 * and {@link lombok.Data}, {@link lombok.AllArgsConstructor}, {@link lombok.NoArgsConstructor},
 * {@link lombok.Builder} to define the entity and automatically generate common methods. </p>
 * <p> This class has a one-to-many relationship with the {@link Url} entity.
 * * The {@code urls} field represents the set of URLs associated with the user.
 * * This relationship is mapped using the {@code @OneToMany} annotation, where each user can have multiple URLs. </p>
 */
@Entity
@Table(schema = "url_shortener", name = "users")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class User {

    /**
     * Unique identifier for the User entity.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The username of the user.
     * This field stores the unique username chosen by the user.
     */
    @Column(length = 50, nullable = false, unique = true)
    private String username;

    /**
     * The password of the user.
     * This field stores the password securely, with a length limit.
     */
    @Column(length = 100, nullable = false)
    private String password;

    /**
     * The URLs associated with this user.
     * This is a one-to-many relationship, where a user can have multiple URLs.
     * This relationship is lazily fetched, meaning that URLs are loaded only when accessed.
     */
    @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Url> urls;
}
