name: Java tests for user with Maven

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give execute permission to mvnw
        run: chmod +x mvnw

      - name: Run tests with Maven
        run: mvn clean test --batch-mode --update-snapshots verify